# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ALCD

on:
  pull_request:
    branches:
      - "new_add_doc"

permissions:
  contents: read
env:
  OTB_RELEASE: 9.1.0
jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: setup python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt install -y --no-install-recommends g++ swig cmake make
        pip install "numpy<2"
        curl https://www.orfeo-toolbox.org/packages/archives/OTB/OTB-$OTB_RELEASE-Linux.tar.gz -o OTB-$OTB_RELEASE-Linux.tar.gz
        tar xvf OTB-$OTB_RELEASE-Linux.tar.gz --one-top-level="/opt/otb"
        source /opt/otb/otbenv.profile
        sh /opt/otb/recompile_bindings.sh
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install rasterio
        pip install pandas
        pip install -U scikit-learn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
